### ISSUE TITLE
Build fails on Windows 7 x64

### ISSUE THREAD

**Issue by mkpankov** [AngryLawyer/SuperMegaTag#2]
This is the [output](http://pastebin.com/VLaUfazG) of Cargo

**Comment by AngryLawyer** [comment]
It can't find your SDL2 and libfreetype6 linking thingies. This took me a while to figure out.

For the SDL2 stuff, you can go here - https://www.libsdl.org/download-2.0.php - and download the Visual C++ development libraries, and drag  the contents of lib/x64 into the root of the repo.

For libfreetype, it's more of a pain. I think it's from http://www.gtk.org/download/win64.php - look for the Freetype Dev 2.4.11 download links, and extract the contents of the lib directory intot the root of the repo.

**Comment by mkpankov** [comment]
Hey!

It builds now. However I needed different freetype stuff. I downloaded [FreeType runtime](http://win32builder.gnome.org/packages/3.6/freetype_2.4.11-1_win64.zip).

Now server starts and prints "listening...",  but the client doesn't. First it complained about zlib1.ddll missing. I downloaded some version of it and put that into root, then it started to throw a Windows "Application Error" message with code (0xc000007b).

Could it be the fact that I have the wrong zlib?

**Comment by AngryLawyer** [comment]
Sounds like it - I forgot that there was a dependency on zlib. Make sure you've got the 64 bit zlib libraries - I've only tried compiling on 32 bit Windows at home.

**Comment by mkpankov** [comment]
I double checked all libraries that I had to download — they're all x64 now. In fact, I even built zlib to make sure of it.

But the error is still the same.

I figured this is due to mixing x64 and x86 images in one process. Happens supermegatag.exe depends on some x86, 32-bit libraries:

```
Dump of file C:\Users\Michael\Documents\GitHub\SuperMegaTag\target\supermegatag.
exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    ADVAPI32.dll
    KERNEL32.dll
    msvcrt.dll
    SHELL32.dll
    USER32.dll
    WS2_32.dll
    SDL2.dll
    libfreetype-6.dll

  Summary

        1000 .CRT
        3000 .bss
        3000 .data
        4000 .debug_abbrev
        1000 .debug_aranges
        8000 .debug_frame
       D6000 .debug_info
       3C000 .debug_line
       10000 .debug_loc
       14000 .debug_pubnames
       16000 .debug_pubtypes
       41000 .debug_ranges
       6F000 .debug_str
        1000 .edata
        5000 .idata
       32000 .pdata
       A1000 .rdata
        8000 .reloc
      46C000 .text
        1000 .tls
       51000 .xdata

C:\Program Files (x86)\Microsoft Visual Studio 12.0>
```

Do you happen to have any idea how do I prevent that? Is it even possible to build for x64 at the moment? :)

**Comment by AngryLawyer** [comment]
I've never tried building 64bit :(

**Comment by mkpankov** [comment]
Ok then, if you don't mind keeping this open I'll keep it updated with my status.

Btw, is there a way to explicitly tell Rust I want 32-bit even though I'm in x64 environment?

**Comment by AngryLawyer** [comment]
Sure.

The way I've done it is by installing the 32bit version of the Rust compiler.

**Comment by mkpankov** [comment]
Cool, will try it then!

14 ноября 2014 г. 12:07:36 GMT+03:00, Tony Aldridge notifications@github.com пишет:

> Sure.
> 
> The way I've done it is by installing the 32bit version of the Rust
> compiler.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/AngryLawyer/SuperMegaTag/issues/2#issuecomment-63027257

—
Regards, 
Michael Pankov
